spring.application.name=demo



# Use INTERNAL URL if your Spring Boot app is also hosted on Render
# Use EXTERNAL URL if running locally


spring.datasource.url=jdbc:postgresql://dpg-d8314fhkh4rs73c810d0-a.oregon-postgres.render.com:5432/hamshub
spring.datasource.username=hamshub_user
spring.datasource.password=wmG8Xy0EsF5QS7KNe2WMVzXeYMdFhmTE
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true